# Generated by Django 2.2 on 2022-06-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='active',
        ),
    ]
